apiVersion: apps/v1
kind: Deployment
metadata: 
  name: to-do-list-deployment
  labels:
    tire: frontend
spec:
  selector:
    matchLabels:
      app: to-do-list
  replicas: 1
  template:
    metadata:
      name: to-do-list
      labels:
        app: to-do-list
    spec:
      containers:
        - name: to-do-list
          image: anirudhabidave/to-do